---
date: 
title: Stan for cognitive science
---

The Stan cognitive science page is meant to serve as a centralized location for all types of work in cognitive science that use the software Stan. 
Anyone can contribute helpful resources related to cognitive science that makes use of Stan through the 
[cognitive science Stan GitHub page](https://github.com/cognitive-science-stan/cognitive-science-stan.github.io). The page for Stan in education might also be relevant https://education-stan.github.io/.


To ask Stan-related questions, please go to [the Stan forum](https://discourse.mc-stan.org/). More specifically, you can use the 
[cognitive-science](https://discourse.mc-stan.org/tag/cognitive-science) tag to ensure that posts are seen by anyone interested in cognitive science as well.

## Events:

- [The Sixth Summer School in Statistical Methods for Linguistics and Psychology](https://vasishth.github.io/smlp2022/), Sept 12-16 2022

## Past events 

- [StanConnect 2021 - Cognitive Science and Neuroscience session](stanconnect2021-cogsci), Nov 19, 2021

## Books and tutorials

For a list of books and tutorials using Stan in cognitive science, see [here](books-tutorials). 


## Cognitive science papers
For a list of cognitive science papers (including conference proceedings) using Stan, see [here](papers). 



## We need your help!
If you want to contribute with papers or issues, check the [README.md file](https://github.com/cognitive-science-stan/cognitive-science-stan.github.io/blob/master/README.md) of the [github repo](https://github.com/cognitive-science-stan/cognitive-science-stan.github.io/). If you want to help to maintain this page, please send an email to <b.nicenboim@tilburguniversity.edu> to be added repo. 
